### ISSUE TITLE
Display ranges from low to high

### ISSUE THREAD

**Issue by waldyrious** [alokmenghrajani/riskybird#3]
Currently, ranges are shown in what IMO is a counter-intuitive way. For example: `?` is shown as `1-0`, `*` is shown as `∞-0`, and `{3,5}` is shown as `5-3`. 

I think such ranges should instead be shown as `0-1`, `0-∞`, and `3-5`, respectively.

**Comment by alokmenghrajani** [comment]
The behavior is correct and reflects the fact that the match is eager. I.e. it regex tries to first match as many characters as possible and then reduces the match size.

**Comment by waldyrious** [comment]
I see. That makes sense, but I'm afraid it makes the UI confusing for the sake of technical correctness. I'd argue that in this case it may be worth being slightly less exact considering the potential for confusion. Maybe a separate mark could be used to denote eagerness?

**Comment by alokmenghrajani** [comment]
Sure, want to create a PR?

**Comment by waldyrious** [comment]
I'd be happy to. How about using a reversed question mark `⸮` for lazy matches, and a regular question mark `?` for greedy ones? In both cases with a proper tooltip explaining what the symbol means there.

With this approach, for instance, the pattern `test*` would change from:

```svg
<text>∞-0</text>
```

into:

```svg
<text>0-∞ <tspan>(⸮)<title>lazy match</title></tspan></text>
```

...and the pattern `test*?` would change from

```svg
<text>0-∞</text>
```

into:

```svg
<text>0-∞ <tspan>(?)<title>greedy match</title></tspan></text>
```

Rendered as images, for easier comparison:

| Lazy: `test*` | Greedy: `test*?` |
|---------------|------------------|
| Before:<br/><img src="https://user-images.githubusercontent.com/478237/53109613-2449d980-3531-11e9-9136-ca95c8b13436.png" width="175"></img><br/>After:<br/><img src="https://user-images.githubusercontent.com/478237/53109799-8d315180-3531-11e9-8937-da504136981a.png" width="175"></img> | Before:<br/><img src="https://user-images.githubusercontent.com/478237/53109789-8acef780-3531-11e9-8826-b4923a9ea4ee.png" width="175"></img><br/>After:<br/><img src="https://user-images.githubusercontent.com/478237/53109790-8acef780-3531-11e9-94fd-2c75c96ce3d3.png" width="175"></img> | |
